site_name: FrameSync
nav:
  - Get Started:
    - Overview: index.md
    - Installation: home/installation.md
  - Tutorial:
    - Pong Game:
      - Overview: tutorial/pong/overview.md
      - Physics 2D: tutorial/pong/parallel2d.md
      - Creating FrameSyncAgent: tutorial/pong/createAgent.md
      - Configuring FrameSyncEngine: tutorial/pong/configEngine.md
      - Configuring FrameSyncGame: tutorial/pong/configGame.md
      - Collecting Player Inputs: tutorial/pong/collectInput.md
      - StaticFrameSyncBehaviour: tutorial/pong/staticFrameSyncBehaviour.md
      - Paddle Owner: tutorial/pong/paddleOwner.md
      - Paddle Movement: tutorial/pong/paddleMovement.md
      - Paddle Position Data: tutorial/pong/paddlePosition.md
      - Ball Manager: tutorial/pong/ballManager.md
      - Playing offline: tutorial/pong/offline.md
  - FrameSync:
    - Important Classes:
      - FrameSyncAgent: frameSync/importantClass/frameSyncAgent.md
  - Physics:
    - physics.md
  - Fixed Math:
    - fixedmath.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
